### PR TITLE
PYTHON-940 Log warning when driver configures an authenticator, but s…

### PR DESCRIPTION
**Pull request by bjmb**
…erver does not request authentication

### CODE REVIEW

**Comment by mambocab** [comment]
+1 after the Travis tests run clean with a changelog entry, looks good!

**Comment by aboudreault** [comment]
LGTM Jim!

**Comment by mambocab** [comment]
Code looks good. I've kicked off a new run of the tests, since it looks like something went wrong last time.

Once the tests run clean, I'm +1 here. Once it's merged to DSE, we should add a test for `DSEGSSAPIAuthProvider`; I'll add a subticket on JIRA.

**Comment by bjmb** [comment]
:+1  test running clean thanks for the reviews, merging.

**Pull request merged**
