### PR TITLE
Fix to remove python 2 & python 3 switches using if statements

### PR DESCRIPTION
**Pull request by vgali7**

### CODE REVIEW

**Comment by bschoening** [comment]
Needs a ↻ Restart Build

**Comment by absurdfarce** [comment]
Greetings @vgali7 and thanks for the contribution!  I restarted the test run as requested by @bschoening; we'll see if we can reliably reproduce the test failures we saw before.

Have you signed the Contributor License Agreement for contributions to DataStax open source projects? If not you can find it at https://cla.datastax.com/. Thanks!

**Comment by bschoening** [comment]
@absurdfarce **appveyor.yml** still references python 2.7 and 3.5.  Should this be updated?

**Comment by vgali7** [comment]
@absurdfarce Thanks for the tip, I've signed the Contributor License Agreement!

**Comment by absurdfarce** [comment]
Hey @vgali7, apologies for not getting back to you sooner.  We're in a rush to address some end-of-quarter updates so I haven't taken a look at this in detail yet.  I should have more time to look it over in the early part of August.

Thanks for your patience!

**Pull request closed without merging**
