### PR TITLE
Python 681: C* 2.0 support removal

### PR DESCRIPTION
**Pull request by aboudreault**
This PR should only be merged for the release 4.0. All unit tests pass.

### CODE REVIEW

**Comment by aboudreault** [comment]
@mambocab @bjmb Please, do not forget to bring your additional changes you did here as well.

**Comment by mambocab** [comment]
Added my changes and Jaume's changes. I'll wait for integration tests to run, then merge.

**Comment by mambocab** [comment]
After some discussion we've recognized that this needs to be released in a major rev. Please don't merge until we've decided to release 4.0 as our next version.

**Comment by mambocab** [comment]
Looks great, I'm +1 on the existing code changes. Thanks for rebasing, Alan!

Grepping around, I found a lot of remaining references to connection pools in internal function names, variable names, and docs. I don't think that blocks merge here, though. Do we want to take that on, or leave the internal references for the moment?

**Comment by aboudreault** [comment]
I will check to fix these references tomorrow Jim.

**Pull request merged**
