### PR TITLE
Add __len__ to BatchStatement

### PR DESCRIPTION
**Pull request by frensjan**
A **len** method on BatchStatement would allow getting the length of the batch without poking around in the 'private' _statements_and_parameters field.

### CODE REVIEW

**Comment by aboudreault** [comment]
Thank you @frensjan. We will take a look at this soon.

**Comment by frensjan** [comment]
any chance this will get merged in?

**Comment by aboudreault** [comment]
Yes, it's planned for the next release.

**Comment by frensjan** [comment]
Super!

**Comment by mambocab** [comment]
I took the liberty of adding a small test. Once CI runs I'll merge. Thank you!

**Pull request merged**
