### PR TITLE
Fix LZ4 test

### PR DESCRIPTION
**Pull request by beltran**

### CODE REVIEW

**Comment by bjmb** [comment]
As @aholmberg noticed, this was failing for older version of lz4 like `0.7.0`

**Comment by mambocab** [comment]
Do we want the duplication here? Would it work to `from cassandra.connection import lz4_block`?

**Comment by mambocab** [comment]
Another way we could deal with this:

https://github.com/datastax/python-driver/tree/replace-lz4-test

The benefit here is that the test and the dereference are right next to each other, so if one gets changed it'll be easier to remember to change the other.

**Comment by mambocab** [comment]
To be clear: I think we could do that and remove the test in its entirety.

**Comment by bjmb** [comment]
I like more your branch and removing the test. But I'd log something and then default to non-compression (like we do if lz4 is not installed) instead of raising an error.

**Comment by mambocab** [comment]
Good idea, sounds like a plan.

**Pull request closed without merging**
