### PR TITLE
Added query_by_keys

### PR DESCRIPTION
**Pull request by bjmb**

### CODE REVIEW

**Comment by bjmb** [comment]
comparison

**Comment by aboudreault** [comment]
Is the execute_concurrent shown in the Graph your new utility function? I guess not?

**Comment by bjmb** [comment]
It `execute_concurrent` from `cassandra.concurrent`, the new function is `query_by_keys`, which is the red line

**Comment by aboudreault** [comment]
ah, Ok thanks. I thought the IN clause was a raw IN query with all keys.

**Comment by bjmb** [comment]
Yeah, I should've clarified a bit. For a reference [this](https://gist.github.com/bjmb/3feac7b3c08929653b93b2d4ff793996) is what I used for the graph. I misconfigured one thing. This is the real graph, the shape is the same but the values of the y-axis change:
comparison

**Comment by bjmb** [comment]
This is a comparison of the function vs a query with a single IN clause:
comparison_2

This is the comparison of the function (which for this particular case sends three queries) vs sending three IN clauses with random keys:
comparison_3
There is no improvement in this case, so maybe targeting the replicas is not an improvement after all

**Comment by aboudreault** [comment]
It looks like we aren't gaining much with this feature. However, It might be interesting to also check C* load with/without query_by_keys.

**Comment by bjmb** [comment]
I tried with a bigger cluster with 9 nodes and there an improvement for the new function:
comparison

**Comment by bjmb** [comment]
Closed in favor of https://github.com/datastax/python-driver/pull/886

**Pull request closed without merging**
