### PR TITLE
Fixed the issue where object creation for model with user defined att…

### PR DESCRIPTION
**Pull request by amishra-1**
…ributes (which are not part of primary key) will fail if the attribute has None value.

### CODE REVIEW

**Comment by aholmberg** [comment]
Thanks for that. Your description refers to Model attributes, while the changes are centered around UDT values. Can you specify the problem a bit more?

Do you have some example code showing the problem? It would be helpful to add that as a test as well.

**Comment by aholmberg** [comment]
https://datastax-oss.atlassian.net/browse/PYTHON-470

**Comment by amishra-1** [comment]
Thanks for the follow up Adam. I have a table definition like this:

```
class Person(Model):
    id = columns.UUID(primary_key=True)
    first_name = columns.Text(partition_key=True)
    last_name = columns.Text(partition_key=True)
    school = columns.UserDefinedType(School)
    primary_email = columns.Text(primary_key=True)
```

here school is the user defined type. Now, when I try to insert a new object where school is not specified

```person = Person(id = uuid.uuid1(), first_name='A', last_name='M', primary_email='a@b.c')
person.save()```

I get below exception:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/ankur/PyCharmProjects/simplr/simppler/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/ankur/PyCharmProjects/simplr/simppler/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/ankur/PyCharmProjects/simplr/simppler/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/ankur/PyCharmProjects/simplr/simppler/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/ankur/PyCharmProjects/simplr/jobshop/simplrservice/management/commands/data_pipeline.py", line 34, in handle
    test_create_table()
  File "/Users/ankur/PyCharmProjects/simplr/jobshop/simplrservice/simppler_cassandra/cassandra_session.py", line 131, in test_create_table
    person.save()
  File "/Users/ankur/PyCharmProjects/simplr/simppler/lib/python2.7/site-packages/cassandra/cqlengine/models.py", line 648, in save
    timeout=self._timeout).save()
  File "/Users/ankur/PyCharmProjects/simplr/simppler/lib/python2.7/site-packages/cassandra/cqlengine/query.py", line 1176, in save
    if self.instance._values[name].changed:
  File "/Users/ankur/PyCharmProjects/simplr/simppler/lib/python2.7/site-packages/cassandra/cqlengine/columns.py", line 793, in changed
    return self.value != self.previous_value or self.value.has_changed_fields()
AttributeError: 'NoneType' object has no attribute 'has_changed_fields'
```

**Comment by amishra-1** [comment]
To me it appears that the lack of None check for value in UDTValueManager is the culprit. Please let me know your thoughts or if you need more details. 

Appreciate the help!

**Comment by aholmberg** [comment]
Thanks for the additional detail.

**Comment by amishra-1** [comment]
Thanks!

**Comment by aholmberg** [comment]
Resolved in #467. Tested in #469.

**Pull request closed without merging**
