### PR TITLE
Add `NO_COMPACT` version to CQL protocol, patch for CASSANDRA-10857.

### PR DESCRIPTION
**Pull request by ifesdjeen**
cc @aholmberg @mambocab

### CODE REVIEW

**Comment by mambocab** [comment]
I've pushed a couple small changes:

- I've added a changelog entry, and
- I moved the new `kwarg` to the end of the `Connection.__init__` call signature to preserve the API for callers that use positional arguments.

Otherwise, looks good to me. If this is definitely the API we want, it looks like we can merge before CASSANDRA-10857 is merged. I'll confirm with the team, but @ifesdjeen let me know when you want this merged. Thanks for the PR!

**Comment by mambocab** [comment]
(Tracking as [PYTHON-839](https://datastax-oss.atlassian.net/browse/PYTHON-839) in JIRA.)

**Comment by ifesdjeen** [comment]
I'd say we can merge it before 10857 is merged, it's completely backwards-compatible.

**Comment by mambocab** [comment]
Awesome, thanks! Merging.

**Pull request merged**
