### PR TITLE
Failing simple query on datetime primary key.

### PR DESCRIPTION
**Pull request by kdeldycke**
Just stumble upon an issue when trying to fetch back a row from a table whose primary key is a datetime.

The unittest from this PR demonstrates how I expect a simple instance to be requested back from its primary key just after adding it.

Instead of passing, the test ends up with a
```
$ CASSANDRA_VERSION=3.0 python ./setup.py nosetests -w tests/integration/cqlengine -x
(...)
2017-06-20 10:11:08,548 DEBUG [management:227]: [Connection: DEFAULT_CONNECTION, Keyspace: cqlengine_test] sync_table creating new table cqlengine_test.date_time_pkmodel
2017-06-20 10:11:08,548 DEBUG [connection:340]: [Connection: DEFAULT_CONNECTION] CREATE TABLE cqlengine_test.date_time_pkmodel ("start_date" timestamp , "stop_date" timestamp , PRIMARY KEY (("start_date")))
2017-06-20 10:11:08,584 DEBUG [libevreactor:348]: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'cqlengine_test', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'date_time_pkmodel'}, stream_id=-1)>
2017-06-20 10:11:08,585 DEBUG [libevreactor:348]: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'cqlengine_test', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'date_time_pkmodel'}, stream_id=-1)>
2017-06-20 10:11:08,586 DEBUG [libevreactor:348]: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'cqlengine_test', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'date_time_pkmodel'}, stream_id=-1)>
2017-06-20 10:11:08,588 DEBUG [thread:62]: Refreshing schema in response to schema change. {'keyspace': u'cqlengine_test', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'date_time_pkmodel'}
2017-06-20 10:11:08,588 DEBUG [thread:62]: [control connection] Waiting for schema agreement
2017-06-20 10:11:08,588 DEBUG [libevreactor:348]: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'cqlengine_test', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'date_time_pkmodel'}, stream_id=-1)>
2017-06-20 10:11:08,592 DEBUG [thread:62]: [control connection] Schemas match
2017-06-20 10:11:08,597 DEBUG [connection:340]: [Connection: DEFAULT_CONNECTION] SELECT COUNT(*) FROM cqlengine_test.date_time_pkmodel LIMIT 10000
2017-06-20 10:11:08,599 WARNING [libevreactor:348]: Server warning: Aggregation query used without partition key
2017-06-20 10:11:08,599 DEBUG [connection:340]: [Connection: DEFAULT_CONNECTION] INSERT INTO cqlengine_test.date_time_pkmodel ("start_date") VALUES (%(0)s)
2017-06-20 10:11:08,601 DEBUG [connection:340]: [Connection: DEFAULT_CONNECTION] SELECT COUNT(*) FROM cqlengine_test.date_time_pkmodel LIMIT 10000
2017-06-20 10:11:08,603 WARNING [libevreactor:348]: Server warning: Aggregation query used without partition key
2017-06-20 10:11:08,604 DEBUG [connection:340]: [Connection: DEFAULT_CONNECTION] SELECT "stop_date" FROM cqlengine_test.date_time_pkmodel WHERE "start_date" = %(0)s LIMIT 10000

ERROR: tests.integration.cqlengine.model.test_model_io:TestModelRoutingKeys.test_datetime_pk_query
  vi +905  tests/integration/cqlengine/model/test_model_io.py  # test_datetime_pk_query
    'start_date', flat=True).all())
  vi +428  cassandra/cqlengine/query.py  # __len__
    self._execute_query()
  vi +463  cassandra/cqlengine/query.py  # _execute_query
    self._result_generator = (i for i in self._execute(self._select_query()))
  vi +448  cassandra/cqlengine/query.py  # _select_query
    fields=self._select_fields(),
  vi +1081 cassandra/cqlengine/query.py  # _select_fields
    ','.join(self._only_fields), ','.join(self._defer_fields)))
QueryException: No fields in select query. Only fields: "start_date", defer fields: "start_date"
```

I'm not sure this issue is specific to datetime columns or the way I fetch back the row. I tried to dig deeper in the code to no avail. Even the raised error doesn't really makes sense to me. :(

Am I right thinking this is the tip of a deeper bug?

### CODE REVIEW

**Comment by aboudreault** [comment]
Thanks for the PR, created a ticket and we will look asap: https://datastax-oss.atlassian.net/browse/PYTHON-779

**Comment by kdeldycke** [comment]
Thanks @aboudreault for the follow-up! :)

**Comment by bjmb** [comment]
@kdeldycke I think you might be onto something although I don't think it would be too serious, with that query you are requesting the field by which you are filtering, which means you already know that field, so it practice this wouldn't be an issue. 

When cqlengine retrieves the list of fields to retrieve it doesn't ask for information it already has and since you are querying for that only field it comes empty. Then it raises that exception because the `SELECT` statements is not querying for any field. If you query for `"stop_date"` or add `"stop_date"` to the list of queried fields it will be fine.

**Comment by bjmb** [comment]
For example the queries:

`DateTimePKModel.objects(start_date=test_instance.start_date).values_list('stop_date', flat=True).first()`
`DateTimePKModel.objects(start_date=test_instance.start_date).values_list('stop_date', 'start_date').first()`

would work

**Comment by bjmb** [comment]
@kdeldycke I'm going to close this since I don't think it's an issue with the driver and I don't think the error message is that far from explaining what's happening. Thanks for the report and the test, the effort is much appreciated.

**Pull request closed without merging**
