### PR TITLE
Quote index name in cql string where necessary

### PR DESCRIPTION
**Pull request by beobal**
See CASSANDRA-12847

### CODE REVIEW

**Comment by aholmberg** [comment]
I'm not sure we can do this blindly since it may not work with older versions, which we still support.

**Comment by beobal** [comment]
> Can we assume that any index identifier that would need quotes could not have existed in earlier versions of Cassandra?

I think so, yes, because prior to CASSANDRA-8365 quotes would've been rejected if supplied, and if a mixed/upper case name was used, it would've been automatically downcased like any other unquoted identifier. So if the identifier requires quoting, we must be talking to C* >= 2.1.3

**Comment by aholmberg** [comment]
Sounds good. I can't figure out why it was ever needed, since `protect_name` is a "maybe" based on identifier case.
Thanks for the PR

**Comment by stef1927** [comment]
This should fix [PYTHON-616](https://datastax-oss.atlassian.net/browse/PYTHON-616), right?

**Comment by aholmberg** [comment]
@stef1927 yes. Thanks for mentioning that link.

**Pull request merged**
