### PR TITLE
PYTHON-719 persisted values should not be set explicit

### PR DESCRIPTION
**Pull request by aboudreault**

### CODE REVIEW

**Comment by aboudreault** [comment]
@bjmb Can we run this PR in Jenkins? I got some issues locally with integration tests.

**Comment by bjmb** [comment]
Sorry, I introduced a bug in the build.yaml but otherwise branches starting with "python-" should build on Jenkins, after this last commit it should build on jenkins.

**Comment by aboudreault** [comment]
Thanks Jaume. I will check that asap.

>

**Comment by mambocab** [comment]
Looks good, and the test results look good to me. Let me know if you'd like me to clean up the conflicts and merge.

**Pull request merged**
