### PR TITLE
Adding validation and fixing timeouts for wide-row integration tests.

### PR DESCRIPTION
**Pull request by GregBestland**
Some of the wide row tests didn't have very good validation, and they were timing out during inserts in jenkins. This should remedy those problems.

### CODE REVIEW

**Comment by kishkaru** [comment]
Everything else LGTM, maybe remove the @since

**Comment by GregBestland** [comment]
I have made the suggested changes. If +1 I will squash and have Adam merge to master.

**Comment by kishkaru** [comment]
:+1:

**Comment by GregBestland** [comment]
Commits have been squashed we can merge this now.

**Pull request merged**
