### PR TITLE
DO NOT MERGE: Add support for clusters with different native and storage ports at each node for CASSANDRA-7544

### PR DESCRIPTION
**Pull request by aweisberg**

### CODE REVIEW

**Comment by mambocab** [comment]
Hey Ariel, if I understand correctly, it sounds like your employer may not be able to let you sign our CLA by the time we want to merge this. I'm going to leave this unmerged with the `cla-missing` tag, in case your employer can sort that out on their end. However, if that doesn't change, my current plan is to write a implementation of our own soon.

**Comment by aweisberg** [comment]
On Thu, Jun 28, 2018, at 2:29 PM, Jim Witschey wrote:
> Hey Ariel, if I understand correctly, it sounds like your employer may
> not be able to let you sign our CLA by the time we want to merge this.
> I'm going to leave this unmerged with the cla-missing tag, in case
> your employer can sort that out on their end. However, if that doesn't
> change, my current plan is to write a implementation of our own soon.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].
Links:

  1. https://github.com/datastax/python-driver/pull/901#issuecomment-401130306

**Comment by aweisberg** [comment]
@mambocab I think we already have the CLA signed. It's the same CLA for the Java driver and all the other drivers. I don't think the bot knows what it is talking about. I'll ask around on my end.

**Comment by mambocab** [comment]
@aweisberg Any word?

**Comment by aweisberg** [comment]
The word I have gotten is not positive. We don't have a CLA for the Java or Python driver and I don't think it's forthcoming for the foreseeable future.

**Comment by mambocab** [comment]
Good to know, thank you. I'm going to leave this PR here, but close it. Thanks for asking around.

**Pull request closed without merging**
