### PR TITLE
Fix timeout in geventreactor

### PR DESCRIPTION
**Pull request by yi719**

### CODE REVIEW

**Comment by yi719** [comment]
I am working on a website with Cassandra. Once in a while I get an OperationTimedOut exception. 
This usually happens on a specific query where I select multiple rows from a specific table. 
That table has a column of type ascii that contains Json blob which can be up to 64k in length but is usually much smaller.

If I understand correctly: there seems to be a problem in handle_read with responses whose length is mutiple of the incoming buffer size(i.e. 4096bytes)

the is_timeout method does not work with gevent's socket timeout.

so maybe we need update the is_timeout  method

**Comment by aholmberg** [comment]
Maybe they changed how a timeout is propagated. Can you specify your gevent version?

Also, is there still some issue with ``handle_read``? You mention it above, but the change set doesn't seem to address anything there.

**Comment by yi719** [comment]
@aholmberg 
I use gevent==1.0.2.

After this change,  OperationTimedOut never show up.

When  responses whose length is mutiple of the incoming buffer size(i.e. 4096bytes),  soccket.timeout will raise. If we do not catch this error in such saturation, self.defunct will be called, then leave the read loop

**Comment by aholmberg** [comment]
Thanks for the additional info. I'm still confused as to why the response size has something to do with socket.timeout. Is there another issue that needs resolution?

**Comment by aholmberg** [comment]
Also, would you mind squashing this into a single commit?

**Comment by yi719** [comment]
> I'm still confused as to why the response size has something to do with socket.timeout. Is there another issue that needs resolution?

In handle_read's while loop, we keep on reading from socket unless len(buf) < self.in_buffer_size, or when response's length is 4096bytes(Cassandra server do not response more data),  we will hit socket.timeout.

>Also, would you mind squashing this into a single commit?
Done

**Comment by aholmberg** [comment]
Thanks for bearing with me. I think I have a complete understanding of the problem now. I've expounded in a follow-on ticket: https://datastax-oss.atlassian.net/browse/PYTHON-429

**Comment by aholmberg** [comment]
Thanks for the contribution!

**Comment by yi719** [comment]
Thanks for your support

**Pull request merged**
