### PR TITLE
PYTHON-348 - previous value tracking in cqlengine

### PR DESCRIPTION
**Pull request by aholmberg**
builds on #373

### CODE REVIEW

**Comment by kdeldycke** [comment]
Thanks @aholmberg for this update ! I'll try to find some time next week to play with it so we can finally solve this issue once for all ! :)

**Comment by aholmberg** [comment]
@kdeldycke still planning to try it out this week, or should I move forward with our internal review and accept your feedback later?

**Comment by kdeldycke** [comment]
Sorry @aholmberg, I'm not going to find enough time to thoroughly evaluate the PR this week.

I quickly skimmed through the code and it looks good to me. All the unit-tests I proposed to track the issue are passing so I don't see any reason to hold the PR back. Feel free to merge it ! :+1:

**Comment by aholmberg** [comment]
No apologies necessary -- you were more than patient for me picking this up. I just wanted to give you a chance since you showed interest.
Thanks for the contribution.

**Comment by kdeldycke** [comment]
Thanks for the merge ! That was fast ! :)

**Pull request merged**
