### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by wenheping**
it could build with cython-0.29

### CODE REVIEW

**Comment by aboudreault** [comment]
Thanks @wenheping. Can you create a Jira ticket  and add the missing changes to complete this PR, see this PR in example: https://github.com/datastax/python-driver/pull/980/files

**Comment by aboudreault** [comment]
@wenheping Don't forget the Jira ticket please. I know it's not super useful in this case, but we try to record everything there for tracking and report purpose inside the organization. You can create one here: https://datastax-oss.atlassian.net

Thanks!

**Comment by mrstell** [comment]
> @wenheping Don't forget the Jira ticket please. I know it's not super useful in this case, but we try to record everything there for tracking and report purpose inside the organization. You can create one here: https://datastax-oss.atlassian.net

https://datastax-oss.atlassian.net/browse/PYTHON-1036

**Comment by aboudreault** [comment]
Thanks for your contribution!

**Pull request merged**
