### PR TITLE
Fix hang when using eventlet and ssl

### PR DESCRIPTION
**Pull request by sigmunau**
The eventlet read loop runs select before each recv call. This will
fail because recv() on an ssl socket might read more data than
requested from the underlying socket in order to have enough context
for decryption. These extra bytes would be returned by the next recv
on the ssl socket, but are not known to underlying socket so select
will hang.

It is my understanding that eventlet implements blocking IO by using
poll under the hood and yielding, so the select should not be
necessary at all

### CODE REVIEW

**Comment by aholmberg** [comment]
Thanks. Will take a look at this for 3.1.
https://datastax-oss.atlassian.net/browse/PYTHON-495

**Comment by sigmunau** [comment]
Slightly revised the fix to solve issues with timeouts when socket is idle for some time

**Comment by aholmberg** [comment]
@sigmunau what level of testing have you done with this? I'm finding the tests not working quite right when I run eventlet_nosetests. Are you just testing manually?

**Comment by aholmberg** [comment]
Thanks for the contribution!

**Pull request merged**
