### PR TITLE
[CQLengine] Set default value of columns on instantiation

### PR DESCRIPTION
**Pull request by kdeldycke**
I just stumbled upon an inconsistency regarding the way `get_changed_columns()` reports columns whose values have been updated.

`get_changed_columns()` in itself works fine. The heavy lifting has been implemented a year ago through #373 and #348, and is upstream since the early days of v3.0.0.

But if the behaviour of [`get_changed_columns()` is thoroughly covered by unit-tests](https://github.com/datastax/python-driver/commit/17f2bc13c2fda731e9de8217790730b151f962ec), there's an edge case when an instance hasn't been persisted yet. This issue only concerns unset columns with a default value.

This issue is demonstrated in the unit-tests attached to this PR. The fix consists in setting the default value of a column right away at instantiation if no value has been provided by the user.

On my machine, no regression have been detected by both the `unit` and `integration` test suites.

### CODE REVIEW

**Comment by aholmberg** [comment]
Thanks. I'll take a look today.

**Comment by aholmberg** [comment]
Thanks for another contribution!

**Comment by kdeldycke** [comment]
Thanks @aholmberg for the review and quick merge! Really happy to contribute! :)

**Comment by kdeldycke** [comment]
As a side note, this PR relates to a very old one: https://github.com/cqlengine/cqlengine/pull/189

**Pull request merged**
