### PR TITLE
PYTHON-409 - fix logging issue in Connection.defunct

### PR DESCRIPTION
**Pull request by aholmberg**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Thanks!

I've hit this issue too which started on 2.6.0 I believe.

**Comment by aholmberg** [comment]
@s0undt3ch thanks for corroborating. Independent of custom log handlers, this should not have been affecting functionality -- just extra logs about the failure. 

The issue has been present since 2.0.0.

We'll have it resolved in the next release.

**Comment by s0undt3ch** [comment]
No functionality was affected, just extra logs as you mentioned.

**Comment by GregBestland** [comment]
+1 on PR looks good.

**Pull request merged**
